### ISSUE TITLE
Cannot find a config at config/config.yaml error when using Docker

### ISSUE THREAD

**Issue by obrienrobert** [cloud-bulldozer/kraken#108]
Using the custom image specified in [issues/105](https://github.com/cloud-bulldozer/kraken/issues/105#issuecomment-862774023) with Docker (version 20.10.6) results in the following error:

```
$ docker run --name=kraken --net=host -v <path-to-kube-config>:/root/.kube/config -v <path-to-config>:/root/kraken/config/config.yaml -d quay.io/chaitanyaenr/kraken:latest

$ docker logs kraken
2021-06-17 09:21:33,172 [INFO] Starting kraken
2021-06-17 09:21:33,172 [ERROR] Cannot find a config at config/config.yaml, please check
```
If I use the following Docker command, it works without error (adding `Z`: [https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label](#configure-the-selinux-label)

```
docker run --name=kraken --net=host -v <path-to-kube-config>:/root/.kube/config:Z -v <path-to-config>:/root/kraken/config/config.yaml:Z -d quay.io/chaitanyaenr/kraken:latest
```
Also, using Podman works expected.

**Comment by paigerube14** [comment]
Think this issue can be closed with the merged PR, correct?
