### ISSUE TITLE
Improve pod killing documentation

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/kraken#112]
The pod killing scenarios use powerfulseal and in our documentation we just link to powerfulseal for all information the user could need. We should update the pod scenario documentation to better explain how to simply update the config files so that the user can change the pod killing scenario as they want, without having to look all over powerfulseal to understand it. 

Main examples should show how to update the pod count, the namespace, and retry/expected count

**Comment by chaitanyaenr** [comment]
https://github.com/cloud-bulldozer/kraken/pull/114 fixed this issue. Thanks.
