### ISSUE TITLE
Kubectl set-context fails because .kube/config file is read-only

### ISSUE THREAD

**Issue by koflerm** [cloud-bulldozer/kraken#132]
I am having a problem with starting kraken in our OpenShift 4.6 cluster:

error: open /root/.kube/config.lock: read-only file system
2021-07-26 13:58:48,953 [ERROR] Failed to run kubectl config set-context --current --namespace=openshift-kraken, error: Command 'kubectl config set-context --current --namespace=openshift-kraken' returned non-zero exit status 1.

The problem is according to your guide the .kube/config file is mounted via configmap to the correct folder. If you now execute a context switch in the code, kubectl tries to write this to the .kube/config file which is not possible as configmaps can only be mounted as read-only into containers. Do you have a solution for that?

**Comment by chaitanyaenr** [comment]
@koflerm Thanks for reporting the issue, https://github.com/cloud-bulldozer/kraken/pull/133 should help with it. Can you test it to see if fixes the issue when you get time please?

**Comment by koflerm** [comment]
@chaitanyaenr Thanks seems to be fixed by your recent pull request. Closing this issue now.
