### ISSUE TITLE
OpenShift Deployment in CrashLoopBackoff State

### ISSUE THREAD

**Issue by koflerm** [cloud-bulldozer/kraken#135]
I see another problem with deploying kraken directly in our OpenShift cluster: After the scenarios are executed, the process terminates. As kraken is deployed as a Deployment, it expects the Pods to run forever. My question would be: Is kraken really supposed to run as a Kubernetes Deployment? Because for me it looks like a terminating Job so the correct Kubernetes Resource would be a Job (or a CronJob? -> regular execution of kraken so e.g. once a day)

**Comment by chaitanyaenr** [comment]
Hi @koflerm, you are right, it needs to run as a Job as it terminates after the end of the run. It's also a good idea to come up with a spec file to run it as CronJob to be able to schedule it on a cadence like you mentioned. Do you want to submit a patch for it?
