### ISSUE TITLE
Feature request: Ability to stop kraken gracefully at some point in future

### ISSUE THREAD

**Issue by vasukulkarni** [cloud-bulldozer/kraken#157]
This is more of a feature request then issue, I am looking to incorporate a single pod failure scenario that runs for variable amount of time(we will not know how long the test runs, it could be set of functional positive tests and keeps increasing as we add more).

At the end of tier1 tests we want to stop the kraken gracefully, so that we can parse the results from the disruption.  We can add some mechanism inside kraken eg: reading external 'stop' file and/or any other mechanism that will help achieve this.

**Comment by chaitanyaenr** [comment]
Fixed by #158 and #168, thanks to @paigerube14. Closing the issue, @vasukulkarni feel free to reopen in case we need to improve the behavior.
