### ISSUE TITLE
Set namespace scenario to only allow label or namespace name

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/kraken#191]
It is a little confusing when using the namespace scenario of what to set for the namespace if you use a label selector and vise versa. Want to update this so you can only set one at a time

Also, want to change the wording of "runs" to delete count

**Comment by paigerube14** [comment]
@chaitanyaenr do we also want to add in functionality that will kill the same namespace a certain number of times?

**Comment by chaitanyaenr** [comment]
> @chaitanyaenr do we also want to add in functionality that will kill the same namespace a certain number of times?

Yes, that would be great @paigerube14.

**Comment by chaitanyaenr** [comment]
Fixed by #194, thanks to @paigerube14!
