### ISSUE TITLE
Chaos scenario to introduce network latency

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/kraken#23]
Kraken needs to support scenarios which introduces communication delays/network latency to simulate degradation or outages in a network and verify if the system especially the critical components like etcd handles it well in terms of leader election/receiving hearbeats from the members.

We need to also support injecting failures such as dropping packets, blocking DNS e.t.c.

**Comment by chaitanyaenr** [comment]
cc: @paigerube14

**Comment by paigerube14** [comment]
> cc: @paigerube14

Taking a look

**Comment by paigerube14** [comment]
I can take this, need to do a lot more research to find different failure scenarios we can preform

**Comment by chaitanyaenr** [comment]
Fixed by #189, thanks to @yogananth-subramanian.
