### ISSUE TITLE
Enable support for Openstack cloud to perform node level chaos tests 

### ISSUE THREAD

**Issue by arcprabh** [cloud-bulldozer/kraken#59]
Issue :

Currently the Kraken tool node level chaos tests are unsupported on an Openstack based OCP cluster.

Solution:

We have enabled support by writing code to connect to and run the node level chaos tests on an Openstack based cluster.
Also, we have updated the node scenarios documentation with instructions for the Openstack cloud type.

**Comment by arcprabh** [comment]
The code commit for this PR is available at https://github.ibm.com/arcprabh/kraken_ocp/commit/e2e2f144fad86aebce750ddcd44b4eb240ea6f65

Please take a look @chaitanyaenr @paigerube14

**Comment by arcprabh** [comment]
PR is https://github.com/cloud-bulldozer/kraken/pull/61

**Comment by mffiedler** [comment]
@arcprabh Thanks for the PR and welcome.   If you can, we'd like to hear a bit about how you are using Kraken.

**Comment by arcprabh** [comment]
Sure @mffiedler 

We run chaos tests on OCP clusters to evaluate the stability and recovery capabilities of the pods and the nodes. We intend to run this as part of our CI pipeline at a regular cadence for the OCP 4.x releases.

**Comment by mffiedler** [comment]
Resolved by #61
