### ISSUE TITLE
kill pods by kill signal instead of deleting them

### ISSUE THREAD

**Issue by duritong** [cloud-bulldozer/kraken#60]
afaiu kraken currently kills pod by deleting them. However this is rather a somewhat graceful termination for the process running in the pod.

It would reflect much more real life scenarios if the processes in the pod's containers would be killed by `kill -9`.

This would show applications arbitrarly terminating and then see how the system reacts to it.

**Comment by paigerube14** [comment]
Ravi did this manually and found issues with cluster recovery on a single node cluster: https://bugzilla.redhat.com/show_bug.cgi?id=1977112

Putting here for my own reference

**Comment by paigerube14** [comment]
Closing issue with the PR being merged! Thanks for the enhancement idea :)

**Comment by paigerube14** [comment]
Closing issue with the PR being merged! Thanks for the enhancement idea :)
