### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by yashashreesuresh** [cloud-bulldozer/kraken#65]
Addition of functional tests to ensure that the PR's don't break the existing functionality of Kraken similar to functional tests in Cerberus. This eases the code review and ensures the commits are non-breaking. 

( PS: It would also enable contributors without cluster to open PR's for minor enhancements confidently :D )

**Comment by chaitanyaenr** [comment]
Fixed by #184, thanks to @paigerube14.
