### ISSUE TITLE
Support to run Kraken on ppc64le architecture

### ISSUE THREAD

**Issue by pravin-dsilva** [cloud-bulldozer/kraken#70]
The scenario is to run Kraken tests on a host having Power (ppc64le) architecture. This would be beneficial to test clusters in environments having only Power and no vm's with other architectures.

 I've run into many pip and yum package dependency issues while installing Kraken directly on a RHEL host running on Power . The Dockerfile which is currently available, only runs on intel architecture.

To solve this, I have created a separate Dockerfile for ppc64le so that the tool can be run without any dependency problems.

**Comment by pravin-dsilva** [comment]
Created PR: https://github.com/cloud-bulldozer/kraken/pull/69
Looking forward to your feedback. Thanks!

**Comment by chaitanyaenr** [comment]
Closing this issue since the PR - https://github.com/cloud-bulldozer/kraken/pull/69 got merged. Thanks.
