### ISSUE TITLE
Questions on running.....

### ISSUE THREAD

**Issue by bmos299** [cloud-bulldozer/kraken#80]
I have some general questions.  

I want to run Kraken in an openshift cluster and point it to another cluster for the chaos testing.
1.  How do I get the .kubeconfig when using OpenShift?
2.  In the config.yaml.  Why is there two different pod_scenarios sections?  Could this be all under one?
```     chaos_scenarios:                                       # List of policies/chaos scenarios to load
        -   pod_scenarios:                                 # List of chaos pod scenarios to load
            - -    scenarios/etcd.yml
            - -    scenarios/regex_openshift_pod_kill.yml
              -    scenarios/post_action_regex.py
        -   node_scenarios:                                # List of chaos node scenarios to load
            -   scenarios/node_scenarios_example.yml
        -   pod_scenarios:
            - -    scenarios/openshift-apiserver.yml
            - -    scenarios/openshift-kube-apiserver.yml   
  ```
            

Thanks.

**Comment by paigerube14** [comment]
Great questions!!
1. So the .kubeconfig file is normally at ${HOME}/.kube/config or if the environment variable is set, it normally would be $KUBECONFIG

2. In the config.yaml file, yes the pod_scenarios sections could be under one. We are just trying to show that it is possible to execute the different types of scenarios in multiple different orders and also multiple times. 

Hope this helps, please let me know if any of this doesn't make sense

**Comment by bmos299** [comment]
Thanks @paigerube14.   I ran the deploy (kraken.yml) and the deploy worked and the pod came up but quickly crashed in python.  I looked at the logs and see this.  Any thoughts?  Also, if it did work....is there where I would go to see the run and results?  
 
```
Barrys-MBP:containers bmosus.ibm.com$ oc get po
NAME                                 READY   STATUS    RESTARTS   AGE
kraken-deployment-5d9f5c77d9-gg56l   1/1     Running   5          4m38s
Barrys-MBP:containers bmosus.ibm.com$ oc logs kraken-deployment-5d9f5c77d9-gg56l
2021-04-08 14:48:35,983 [INFO] Starting kraken
2021-04-08 14:48:35,989 [INFO] Initializing client to talk to the Kubernetes cluster
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

Traceback (most recent call last):
  File "run_kraken.py", line 403, in <module>
    main(options.cfg)
  File "run_kraken.py", line 309, in main
    kubecli.find_kraken_node()
  File "/root/kraken/kraken/kubernetes/client.py", line 180, in find_kraken_node
    pod_json = json.loads(pod_json_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by paigerube14** [comment]
I usually don't run it using the deploy; I run using a locally cloned version. I know we have been having issues using the deploy (see here: https://github.com/cloud-bulldozer/kraken/issues/79) we are working on trying to get a fix for that. 

Normally (if things worked) you would see the run and results right in the logs there that you are looking at or in the terminal, if running locally. It'll print off which scenario it is running and the results ( see below for example) 


```

% python run_kraken.py 
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

2021-04-08 10:59:07,010 [INFO] Starting kraken
2021-04-08 10:59:07,016 [INFO] Initializing client to talk to the Kubernetes cluster
2021-04-08 10:59:10,910 [INFO] Fetching cluster info
2021-04-08 10:59:11,651 [INFO] 
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.0-0.nightly-2021-04-06-162113   True        False         22h     Cluster version is 4.8.0-0.nightly-2021-04-06-162113
Kubernetes control plane is running at https://api.qe-pr-aws9.qe.devcluster.openshift.com:6443

2021-04-08 10:59:11,652 [INFO] Daemon mode not enabled, will run through 1 iterations

2021-04-08 10:59:11,652 [INFO] Executing scenarios for iteration 0
2021-04-08 10:59:16 INFO __main__ verbosity: None; log level: INFO; handler level: INFO
2021-04-08 10:59:16 INFO __main__ Creating kubernetes client with config /Users/prubenda/.kube/config from --kubeconfig flag
2021-04-08 10:59:16 INFO k8s_client Initializing with config: /Users/prubenda/.kube/config
2021-04-08 10:59:16 INFO __main__ No cloud driver - some functionality disabled
2021-04-08 10:59:16 INFO __main__ Using stdout metrics collector
2021-04-08 10:59:16 INFO __main__ NOT starting the UI server
2021-04-08 10:59:16 INFO __main__ STARTING AUTONOMOUS MODE
2021-04-08 10:59:18 INFO scenario.delete etcd pod Starting scenario 'delete etcd pods' (2 steps)
2021-04-08 10:59:18 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 3
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 1
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Pod killed: [pod #1 name=etcd-ip-10-0-168-189.us-east-2.compute.internal namespace=openshift-etcd containers=3 ip=10.0.168.189 host_ip=10.0.168.189 state=Running labels:app=etcd,etcd=true,k8s-app=etcd,revision=3 annotations:kubernetes.io/config.hash=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.mirror=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.seen=2021-04-07T16:02:58.149983648Z,kubernetes.io/config.source=file]
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
2021-04-08 10:59:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
2021-04-08 10:59:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Initial set length: 2
2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
2021-04-08 10:59:49 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
2021-04-08 10:59:49 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
2021-04-08 11:00:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
2021-04-08 11:00:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Initial set length: 3
2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 3
2021-04-08 11:00:49 INFO scenario.delete etcd pod Scenario finished
2021-04-08 11:00:49 INFO policy_runner All done here!

2021-04-08 11:00:50,070 [INFO] Scenario: scenarios/etcd.yml has been successfully injected!
2021-04-08 11:00:50,071 [INFO] Waiting for the specified duration: 60
2021-04-08 11:01:50,073 [INFO] 
```

**Comment by bmos299** [comment]
@paigerube14 it looks like you co-authored the blog i am using, https://www.openshift.com/blog/introduction-to-kraken-a-chaos-tool-for-openshift/kubernetes.  I am just trying to find a simple way to use a .kubeconfig with openshift as I usually just login with the token.

**Comment by mffiedler** [comment]
The kube config is generated a couple of ways.   After install, the system:admin kubeconfig for OCP installs is in <install_dir>/auth/kubeconfig.   If you are using oc login -u or oc login -t it will be in <home_dir>/.kube/config unless you are using the "oc config" command to do advanced context switching.

It sounds like your issue is with getting a kube config for a separate cluster into the cluster where Kraken is running.  Have you tried creating a ConfigMap with a valid kube config for the remote cluster you are trying to access with Kraken?   See https://github.com/cloud-bulldozer/kraken/tree/master/containers.    I would also suggest trying to run Kraken non-containerized (from a git clone) first and then migrating a working config to ConfigMaps and containers.    Let me know if I am mis-understanding the issue.

**Comment by bmos299** [comment]
I think the .kubeconfig also had to do with our environment.  I ran kraken and now got the below results. Is this a successful run? If so, I want to start layering in cerberus, etc.  ``` Barrys-MBP:containers bmosus.ibm.com$ oc logs kraken-deployment-5d9f5c77d9-fsfjt -f
2021-04-09 11:22:57,696 [INFO] Starting kraken
2021-04-09 11:22:57,704 [INFO] Initializing client to talk to the Kubernetes cluster
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.kraken-cp4i.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2021-04-09 11:22:59,199 [INFO] Fetching cluster info
2021-04-09 11:23:53,840 [INFO] 
I0409 11:23:00.483613      10 request.go:655] Throttling request took 1.172247354s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/management.apiconnect.ibm.com/v1beta1?timeout=32s
I0409 11:23:10.494320      10 request.go:655] Throttling request took 5.995833969s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/console.openshift.io/v1?timeout=32s
I0409 11:23:20.494341      10 request.go:655] Throttling request took 15.995727569s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/ceph.rook.io/v1?timeout=32s
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.16    True        False         41h     Cluster version is 4.6.16
I0409 11:23:27.811855      25 request.go:655] Throttling request took 1.162255933s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/management.apiconnect.ibm.com/v1beta1?timeout=32s
I0409 11:23:37.818904      25 request.go:655] Throttling request took 5.99537817s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/console.openshift.io/v1?timeout=32s
I0409 11:23:47.818944      25 request.go:655] Throttling request took 15.995271607s, request: GET:https://api.kraken-cp4i.cp.fyre.ibm.com:6443/apis/network.openshift.io/v1?timeout=32s
Kubernetes control plane is running at https://api.kraken-cp4i.cp.fyre.ibm.com:6443

2021-04-09 11:23:53,841 [INFO] Daemon mode not enabled, will run through 1 iterations

2021-04-09 11:23:53,841 [INFO] Executing scenarios for iteration 0
2021-04-09 11:23:54,276 [INFO] Scenario: scenarios/etcd.yml has been successfully injected!
2021-04-09 11:23:54,276 [INFO] Waiting for the specified duration: 60
error: unexpected EOF
Barrys-MBP:containers bmosus.ibm.com$  ```

**Comment by bmos299** [comment]
I have it running now. It looks like it is exiting due to the cloud type in node_scenarios: `cloud_type:`.

It looks like the cloud can be set to aws, gcp, openstack, and azure.   I have two environments I run on.

**Comment by chaitanyaenr** [comment]
@bmos299 The current supported environments include AWS, GCP, OpenStack and Azure like you mentioned: https://github.com/cloud-bulldozer/kraken/blob/master/docs/node_scenarios.md. @jaredoconnell has a PR open which adds baremetal support. 

There are just a couple of node scenarios like reboot/stop etc. that depends on the cloud on top of which OCP is running since they use the cloud API for the operation, the pod based scenarios, time based scenarios and a couple of node based scenarios including the node crash ( fork bomb ) and kubelet reboot can run independent of the cloud platform. Also, Litmus scenarios can also be triggered using Kraken: https://github.com/cloud-bulldozer/kraken/blob/master/docs/litmus_scenarios.md.  

Can you create an issue for IBM cloud when you get time please? This way it will be under our radar.

**Comment by bmos299** [comment]
@chaitanyaenr I see that @seanogor opened #84 .  Is this the requirement you need?

**Comment by chaitanyaenr** [comment]
@bmos299 Yes, the issues opened by @seanogor should help with tracking it. We would definitely appreciate any help with it. Thanks.

**Comment by seanogor** [comment]
> I usually don't run it using the deploy; I run using a locally cloned version. I know we have been having issues using the deploy (see here: https://github.com/cloud-bulldozer/kraken/issues/79) we are working on trying to get a fix for that. 
> 
> Normally (if things worked) you would see the run and results right in the logs there that you are looking at or in the terminal, if running locally. It'll print off which scenario it is running and the results ( see below for example) 
> 
> 
> ```
> 
> % python run_kraken.py 
>  _              _              
> | | ___ __ __ _| | _____ _ __  
> | |/ / '__/ _` | |/ / _ \ '_ \ 
> |   <| | | (_| |   <  __/ | | |
> |_|\_\_|  \__,_|_|\_\___|_| |_|
>                                
> 
> 2021-04-08 10:59:07,010 [INFO] Starting kraken
> 2021-04-08 10:59:07,016 [INFO] Initializing client to talk to the Kubernetes cluster
> 2021-04-08 10:59:10,910 [INFO] Fetching cluster info
> 2021-04-08 10:59:11,651 [INFO] 
> NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
> version   4.8.0-0.nightly-2021-04-06-162113   True        False         22h     Cluster version is 4.8.0-0.nightly-2021-04-06-162113
> Kubernetes control plane is running at https://api.qe-pr-aws9.qe.devcluster.openshift.com:6443
> 
> 2021-04-08 10:59:11,652 [INFO] Daemon mode not enabled, will run through 1 iterations
> 
> 2021-04-08 10:59:11,652 [INFO] Executing scenarios for iteration 0
> 2021-04-08 10:59:16 INFO __main__ verbosity: None; log level: INFO; handler level: INFO
> 2021-04-08 10:59:16 INFO __main__ Creating kubernetes client with config /Users/prubenda/.kube/config from --kubeconfig flag
> 2021-04-08 10:59:16 INFO k8s_client Initializing with config: /Users/prubenda/.kube/config
> 2021-04-08 10:59:16 INFO __main__ No cloud driver - some functionality disabled
> 2021-04-08 10:59:16 INFO __main__ Using stdout metrics collector
> 2021-04-08 10:59:16 INFO __main__ NOT starting the UI server
> 2021-04-08 10:59:16 INFO __main__ STARTING AUTONOMOUS MODE
> 2021-04-08 10:59:18 INFO scenario.delete etcd pod Starting scenario 'delete etcd pods' (2 steps)
> 2021-04-08 10:59:18 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 3
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 1
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Pod killed: [pod #1 name=etcd-ip-10-0-168-189.us-east-2.compute.internal namespace=openshift-etcd containers=3 ip=10.0.168.189 host_ip=10.0.168.189 state=Running labels:app=etcd,etcd=true,k8s-app=etcd,revision=3 annotations:kubernetes.io/config.hash=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.mirror=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.seen=2021-04-07T16:02:58.149983648Z,kubernetes.io/config.source=file]
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> 2021-04-08 10:59:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> 2021-04-08 10:59:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> 2021-04-08 10:59:49 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> 2021-04-08 10:59:49 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> 2021-04-08 11:00:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> 2021-04-08 11:00:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
> 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Initial set length: 3
> 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 3
> 2021-04-08 11:00:49 INFO scenario.delete etcd pod Scenario finished
> 2021-04-08 11:00:49 INFO policy_runner All done here!
> 
> 2021-04-08 11:00:50,070 [INFO] Scenario: scenarios/etcd.yml has been successfully injected!
> 2021-04-08 11:00:50,071 [INFO] Waiting for the specified duration: 60
> 2021-04-08 11:01:50,073 [INFO] 
> ```
> 

How do you enable this level of debugging, can you pass in a parameter in the cerberus/kraken configuration maps?

**Comment by seanogor** [comment]
> @bmos299 Yes, the issues opened by @seanogor should help with tracking it. We would definitely appreciate any help with it. Thanks.

Will open a case to track, if you have an IBM contact we can add to the case...

**Comment by chaitanyaenr** [comment]
> > I usually don't run it using the deploy; I run using a locally cloned version. I know we have been having issues using the deploy (see here: #79) we are working on trying to get a fix for that.
> > Normally (if things worked) you would see the run and results right in the logs there that you are looking at or in the terminal, if running locally. It'll print off which scenario it is running and the results ( see below for example)
> > ```
> > 
> > % python run_kraken.py 
> >  _              _              
> > | | ___ __ __ _| | _____ _ __  
> > | |/ / '__/ _` | |/ / _ \ '_ \ 
> > |   <| | | (_| |   <  __/ | | |
> > |_|\_\_|  \__,_|_|\_\___|_| |_|
> >                                
> > 
> > 2021-04-08 10:59:07,010 [INFO] Starting kraken
> > 2021-04-08 10:59:07,016 [INFO] Initializing client to talk to the Kubernetes cluster
> > 2021-04-08 10:59:10,910 [INFO] Fetching cluster info
> > 2021-04-08 10:59:11,651 [INFO] 
> > NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
> > version   4.8.0-0.nightly-2021-04-06-162113   True        False         22h     Cluster version is 4.8.0-0.nightly-2021-04-06-162113
> > Kubernetes control plane is running at https://api.qe-pr-aws9.qe.devcluster.openshift.com:6443
> > 
> > 2021-04-08 10:59:11,652 [INFO] Daemon mode not enabled, will run through 1 iterations
> > 
> > 2021-04-08 10:59:11,652 [INFO] Executing scenarios for iteration 0
> > 2021-04-08 10:59:16 INFO __main__ verbosity: None; log level: INFO; handler level: INFO
> > 2021-04-08 10:59:16 INFO __main__ Creating kubernetes client with config /Users/prubenda/.kube/config from --kubeconfig flag
> > 2021-04-08 10:59:16 INFO k8s_client Initializing with config: /Users/prubenda/.kube/config
> > 2021-04-08 10:59:16 INFO __main__ No cloud driver - some functionality disabled
> > 2021-04-08 10:59:16 INFO __main__ Using stdout metrics collector
> > 2021-04-08 10:59:16 INFO __main__ NOT starting the UI server
> > 2021-04-08 10:59:16 INFO __main__ STARTING AUTONOMOUS MODE
> > 2021-04-08 10:59:18 INFO scenario.delete etcd pod Starting scenario 'delete etcd pods' (2 steps)
> > 2021-04-08 10:59:18 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 3
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 1
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Pod killed: [pod #1 name=etcd-ip-10-0-168-189.us-east-2.compute.internal namespace=openshift-etcd containers=3 ip=10.0.168.189 host_ip=10.0.168.189 state=Running labels:app=etcd,etcd=true,k8s-app=etcd,revision=3 annotations:kubernetes.io/config.hash=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.mirror=5a0603be-bcf3-485e-a99d-8a25d514a145,kubernetes.io/config.seen=2021-04-07T16:02:58.149983648Z,kubernetes.io/config.source=file]
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> > 2021-04-08 10:59:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> > 2021-04-08 10:59:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> > 2021-04-08 10:59:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> > 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> > 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> > 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> > 2021-04-08 10:59:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> > 2021-04-08 10:59:49 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> > 2021-04-08 10:59:49 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> > 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> > 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Matched 2 pods for selector k8s-app=etcd in namespace openshift-etcd
> > 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Initial set length: 2
> > 2021-04-08 11:00:19 INFO action_nodes_pods.delete etcd pod Filtered set length: 2
> > 2021-04-08 11:00:19 ERROR action_nodes_pods.delete etcd pod Expected 3 pods, got 2
> > 2021-04-08 11:00:19 WARNING scenario.delete etcd pod Failure in action. Sleeping 30 and retrying
> > 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matching 'labels' {'labels': {'namespace': 'openshift-etcd', 'selector': 'k8s-app=etcd'}}
> > 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Matched 3 pods for selector k8s-app=etcd in namespace openshift-etcd
> > 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Initial set length: 3
> > 2021-04-08 11:00:49 INFO action_nodes_pods.delete etcd pod Filtered set length: 3
> > 2021-04-08 11:00:49 INFO scenario.delete etcd pod Scenario finished
> > 2021-04-08 11:00:49 INFO policy_runner All done here!
> > 
> > 2021-04-08 11:00:50,070 [INFO] Scenario: scenarios/etcd.yml has been successfully injected!
> > 2021-04-08 11:00:50,071 [INFO] Waiting for the specified duration: 60
> > 2021-04-08 11:01:50,073 [INFO] 
> > ```
> 
> How do you enable this level of debugging, can you pass in a parameter in the cerberus/kraken configuration maps?

The logs of the pod should print the detailed information of the run @bmos299. if not we definitely need to fix it :-)

**Comment by chaitanyaenr** [comment]
> Will open a case to track, if you have an IBM contact we can add to the case...

That would to great @seanogor, we don't have an IBM contact.

**Comment by seanogor** [comment]
Could you comment on the debugging I mentioned?

**Comment by chaitanyaenr** [comment]
@seanogor The logs have the debugging information: 1) standalone kraken run will print the logs to the stdout 2) podman/docker logs -f <container> can be used to stream the logs in case of containerized version 3) oc/kubectl logs -f <pod> can be used to stream the logs.

**Comment by bmos299** [comment]
Thanks for the help. Closing.
