### ISSUE TITLE
Running Containerized Version Link goes to nothing

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/kraken#81]
On the [containers page](https://github.com/cloud-bulldozer/kraken/tree/master/containers), the link under the **Run containerized version** just goes to the kraken home page. 

It is supposed to go to [this](https://github.com/cloud-bulldozer/kraken/blob/master/containers/build_own_image-README.md) page correct?

**Comment by chaitanyaenr** [comment]
Fixed by #82, thanks to @paigerube14.
