### ISSUE TITLE
Cerberus go/no-go signal being consumed prior to sleeping for wait duration in litmus scenarios

### ISSUE THREAD

**Issue by gclendinning02** [cloud-bulldozer/kraken#89]
Hey all,

We've been doing some chaos testing using kraken and we've noticed some signalling issues from cerberus when running litmus scenarios. In our case we are running a pod network loss experiment that is reporting a successful result, but cerberus is returning a no-go signal immediately after due to liveness check failure restarting the pod during the experiment.

After looking at the code it seems the ordering for checking the signal is wrong in the litmus_scenarios function:
```
cerberus_integration(config)
logging.info("Waiting for the specified duration: %s" % wait_duration)
time.sleep(wait_duration)
```

In the other functions cerberus is checked after the wait duration:
```
logging.info("Waiting for the specified duration: %s" % (wait_duration))
time.sleep(wait_duration)
cerberus_integration(config)
```

**Comment by chaitanyaenr** [comment]
@gclendinning02 Thanks for reporting the issue, it should be fixed now thanks to @paigerube14. Please feel free to let us in case of any issues.

**Comment by gclendinning02** [comment]
Cheers! Will do.
