### ISSUE TITLE
Grafana Dashboard - Bad Gateway

### ISSUE THREAD

**Issue by kmlefebv** [cloud-bulldozer/kraken#95]
I've enabled the Grafana dashboard on the config.yaml file and I get an  `Bad Gateway` message on all of the dashboards. I've tested it on an IBM ROKS cluster as well as an AWS cluster and encountered the same problem.
![image](https://user-images.githubusercontent.com/47637635/116461968-ea726d00-a836-11eb-818e-f8cf05f1410e.png)

**Comment by jtaleric** [comment]
is this with 4.8 latest?

**Comment by kmlefebv** [comment]
Are you asking about which OCP version we are using? The Kraken host is currently using: 
OpenShift version: 4.6.23

**Comment by chaitanyaenr** [comment]
@kmlefebv looks like it was not able to grab the prometheus url to add it as a datasource. $ oc get secrets -n openshift-monitoring grafana-datasources -o go-template='{{index .data "prometheus.yaml" | base64decode }}' | jq '.datasources[0].url'
command is used to get it but there's a problem with jq like you mentioned in https://github.com/cloud-bulldozer/kraken/issues/92 which might be causing it to fail. https://github.com/cloud-bulldozer/kraken/pull/93 should fix it.

**Comment by chaitanyaenr** [comment]
Closing this issue now that #93 got merged. @kmlefebv Please feel free to reopen the issue in case it didn't fix the problem that we are seeing with Grafana dashboard reading data from Prometheus. Thanks.
